# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ares.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'ares.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nares.proto\x12\x08\x61res.ipc\"M\n\x08LogTrace\x12\r\n\x05level\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0e\n\x06module\x18\x04 \x01(\t\"\\\n\x0f\x41pprovalRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07options\x18\x03 \x03(\t\x12\x17\n\x0ftimeout_seconds\x18\x04 \x01(\x05\".\n\x10\x41pprovalResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x63hoice\x18\x02 \x01(\t\"<\n\x0bStateChange\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"*\n\x0c\x43onfigUpdate\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x8e\x02\n\x08\x45nvelope\x12\'\n\tlog_trace\x18\x01 \x01(\x0b\x32\x12.ares.ipc.LogTraceH\x00\x12\x35\n\x10\x61pproval_request\x18\x02 \x01(\x0b\x32\x19.ares.ipc.ApprovalRequestH\x00\x12\x37\n\x11\x61pproval_response\x18\x03 \x01(\x0b\x32\x1a.ares.ipc.ApprovalResponseH\x00\x12-\n\x0cstate_change\x18\x04 \x01(\x0b\x32\x15.ares.ipc.StateChangeH\x00\x12/\n\rconfig_update\x18\x05 \x01(\x0b\x32\x16.ares.ipc.ConfigUpdateH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ares_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGTRACE']._serialized_start=24
  _globals['_LOGTRACE']._serialized_end=101
  _globals['_APPROVALREQUEST']._serialized_start=103
  _globals['_APPROVALREQUEST']._serialized_end=195
  _globals['_APPROVALRESPONSE']._serialized_start=197
  _globals['_APPROVALRESPONSE']._serialized_end=243
  _globals['_STATECHANGE']._serialized_start=245
  _globals['_STATECHANGE']._serialized_end=305
  _globals['_CONFIGUPDATE']._serialized_start=307
  _globals['_CONFIGUPDATE']._serialized_end=349
  _globals['_ENVELOPE']._serialized_start=352
  _globals['_ENVELOPE']._serialized_end=622
# @@protoc_insertion_point(module_scope)
